FROM golang:1.12.0

ARG PROJECT_DIR=/go/src/gitlab.com/codelittinc/golang-interview-project-ryan-bennett

RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR
COPY . .
WORKDIR $PROJECT_DIR/app

CMD ["go", "run", "main.go"]